import { jsPDF } from "jspdf";

export const generateRealPdf = (userData) => {
  const doc = new jsPDF();
  const applicationId = "SETU-" + Math.floor(100000 + Math.random() * 900000);
  
  // Header
  doc.setFillColor(2, 132, 199); 
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("SETU AI - Government of India", 105, 20, { align: "center" });
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Application Form (Digitally Generated)", 105, 30, { align: "center" });

  // Add Application ID Barcode / Text
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Tracking ID: ${applicationId}`, 150, 48);
  doc.setTextColor(150, 150, 150);
  doc.text("Verified by CSC Network", 150, 53);

  // DIGITAL WATERMARK 
  doc.setTextColor(235, 235, 235); 
  doc.setFontSize(40);
  doc.setFont("helvetica", "bold");
  doc.text("SETU AI VERIFIED", 40, 150, { angle: 45 });

  // Body / Section Title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFillColor(240, 240, 240);
  doc.rect(20, 60, 170, 10, 'F');
  doc.text("Applicant Details", 25, 67);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 70, 190, 70);

  // Data Box
  doc.setFontSize(12);
  let yPosition = 80;
  const boxStartY = 75;
  
  if (userData && Object.keys(userData).length > 0) {
    for (const [key, value] of Object.entries(userData)) {
     
      const safeValue = String(value).replace(/[^\x00-\x7F]/g, "[Requires English Translation]");
      const formattedKey = key.charAt(0).toUpperCase() + key.slice(1).replace('_', ' ');
      
      doc.setFont("helvetica", "bold");
      doc.text(`${formattedKey}:`, 25, yPosition);
      doc.setFont("helvetica", "normal");
      doc.text(safeValue, 70, yPosition);
      
      // Divider line
      doc.setDrawColor(230, 230, 230);
      doc.line(20, yPosition + 3, 190, yPosition + 3);
      yPosition += 12;
    }
  } else {
    doc.text("Data pending...", 25, yPosition);
    yPosition += 12;
  }
  
  // Outer Border for Data
  const boxEndY = yPosition - 5;
  doc.setDrawColor(150, 150, 150);
  doc.rect(20, boxStartY, 170, boxEndY - boxStartY); 

  // Declaration
  yPosition += 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Declaration:", 20, yPosition);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("I hereby declare that the information provided above is true to the best of my knowledge.", 20, yPosition + 7);
  
  // Signature Block
  doc.setDrawColor(0, 0, 0);
  doc.line(130, yPosition + 35, 190, yPosition + 35);
  doc.text("Applicant's Signature / Thumbprint", 130, yPosition + 40);

  return doc.output('bloburl');
};

export const generateRtiPdf = (userData, rtiText) => {
  const doc = new jsPDF();
  
  // Header Section - RED for Grievance
  doc.setFillColor(186, 25, 25); 
  doc.rect(0, 0, 210, 45, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("SETU AI - Grievance Guardian", 105, 20, { align: "center" });
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Right to Information (RTI) / Official Complaint", 105, 30, { align: "center" });

  // Metadata
  const grievanceId = "RTI-" + Math.floor(100000 + Math.random() * 900000);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Grievance ID: ${grievanceId}`, 130, 60);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60);

  // AI Generated Text
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("To The Public Information Officer / Nodal Officer,", 20, 80);
  
  // Auto-wrap the text generated by the AI
  const splitText = doc.splitTextToSize(rtiText || "I am filing a formal grievance regarding a delayed scheme benefit. Please provide the status immediately.", 170);
  doc.text(splitText, 20, 95);

  // Sign off
  doc.setFont("helvetica", "bold");
  doc.text("Applicant Details:", 20, 140);
  doc.setFont("helvetica", "normal");
  let y = 150;
  for (const [key, value] of Object.entries(userData || {})) {
    doc.text(`${key.toUpperCase()}: ${value}`, 20, y);
    y += 10;
  }
  
  doc.setDrawColor(0, 0, 0);
  doc.line(130, 200, 190, 200);
  doc.text("Applicant Signature", 135, 205);

  return doc.output('bloburl');
};